Create ForwardList.cpp
DoomzD/ForwardList pull request #1
Opened 2017-12-24 15:53 UTC by DoomzD

2017-12-25 20:03 UTC, ifsmirnov requested changes
Из общих замечаний:

1) не надо делать лишних new, нужно манипулировать указателями;

2) вместо названия tmp всегда можно придумать что-то более хорошее. newNode, nextNode и так далее.

2017-12-25 20:03 UTC, ifsmirnov commented on ForwardList.cpp
> +    void add(const int x) {
Лучше push_front, чтобы было понятно, куда добавляется элемент.

2017-12-25 20:03 UTC, ifsmirnov commented on ForwardList.cpp
> +        tmp->data = x;
Можно добавить в Node конструктор и заменить эти три строчки на одну. Или даже сейчас сделать `Node* tmp = new Node{x, head}`.

2017-12-25 20:03 UTC, ifsmirnov commented on ForwardList.cpp
> +    void show() const {
print, output.

2017-12-25 20:03 UTC, ifsmirnov commented on ForwardList.cpp
> +        while (1) {
while (true)

2017-12-25 20:03 UTC, ifsmirnov commented on ForwardList.cpp
> +        while (leftNode != nullptr && rightNode != nullptr) {
В следующих 15 строках два блока повторяются по два раза. Можно сделать в цикле побольше ифов, но избежать лишнего копирования.

2017-12-25 20:03 UTC, ifsmirnov commented on ForwardList.cpp
> +                tmp.add(leftNode->data);
add вызывает new. У тебя происходит n log n вызовов new для сортировки. Ни должно происходить ни одного.

2017-12-25 20:03 UTC, ifsmirnov commented on ForwardList.cpp
> +
Пустая строка.

2017-12-25 20:03 UTC, ifsmirnov commented on ForwardList.cpp
> +    void merge(List &left, List &right) {
1) почему left и right принимаются по ссылке?
2) по хорошему, функция должна выглядеть как `List merge(List lhs, List rhs)`. Сейчас она записывает результат merge двух списков в текущий список. Это совсем не очевидно из сигнатуры и названия.

2018-01-07 07:20 UTC, DoomzD commented
Немного не понял, как можно уменьшить количество копирований в том блоке.
И ещё пару вопросов: 
1. Можно ли ставить такие ограничения в деструкторе?
2. Можно ли использовать названия переменных как в строках 119-120?
И да, в целом, мы придерживаемся какого-то кодстайла относительно названий переменных (не считая "говорящих" названий), или можно писать как душе угодно (всё одним стайлом конечно)?

2018-01-24 21:30 UTC, ifsmirnov requested changes
Трюк с isAllocated_ мне совсем не нравится, но с ним можно смириться.

2018-01-24 21:30 UTC, ifsmirnov commented on ForwardList.cpp
> +const int BIG_INT = (1ll << 30) - 1;
во-первых, numeric_limits
во-вторых, нигде не используется

2018-01-24 21:30 UTC, ifsmirnov commented on ForwardList.cpp
> +    void push_front(Node* newNode) {
Node* node
Этот метод не должен быть публичным.

2018-01-24 21:30 UTC, ifsmirnov commented on ForwardList.cpp
> +        while (head_ != nullptr) {
Лучше проверить isAllocated_ один раз перед циклом.

2018-01-24 21:30 UTC, ifsmirnov commented on ForwardList.cpp
> +        Node* prevNode = nullptr;
А вот тут Node в названии избыточно. В принципе, тут и cur нормально подходит.

2018-01-24 21:30 UTC, ifsmirnov commented on ForwardList.cpp
> +        Node* thisCurNode = head_;
Нет, это ещё хуже, чем просто cur.

2018-01-24 21:30 UTC, ifsmirnov commented on ForwardList.cpp
> +        while (thisCurNode != nullptr) {
А зачем вообще перекидывать данные по одному? Почему нельзя просто сделать *this = merged или скопировать поля вручную?

2018-02-06 13:44 UTC, ifsmirnov approved these changes
LGTM

2018-02-26 19:38 UTC, merged